// https://colors.eva.design/

export const colorScheme = {
  "color-primary-100": "#D6E4FF",
  "color-primary-200": "#ADC8FF",
  "color-primary-300": "#84A9FF",
  "color-primary-400": "#6690FF",
  "color-primary-500": "#3366FF",
  "color-primary-600": "#254EDB",
  "color-primary-700": "#1939B7",
  "color-primary-800": "#102693",
  "color-primary-900": "#091A7A",
  "color-success-100": "#EEFCD3",
  "color-success-200": "#DAF9A8",
  "color-success-300": "#BBED79",
  "color-success-400": "#9ADC56",
  "color-success-500": "#6EC625",
  "color-success-600": "#54AA1B",
  "color-success-700": "#3D8E12",
  "color-success-800": "#29720B",
  "color-success-900": "#1B5F07",
  "color-info-100": "#D4F6FF",
  "color-info-200": "#AAE9FF",
  "color-info-300": "#7FD8FF",
  "color-info-400": "#60C5FF",
  "color-info-500": "#2BA6FF",
  "color-info-600": "#1F81DB",
  "color-info-700": "#1561B7",
  "color-info-800": "#0D4493",
  "color-info-900": "#08307A",
  "color-warning-100": "#FFF7CC",
  "color-warning-200": "#FFED99",
  "color-warning-300": "#FFE066",
  "color-warning-400": "#FFD33F",
  "color-warning-500": "#FFBF00",
  "color-warning-600": "#DB9E00",
  "color-warning-700": "#B77F00",
  "color-warning-800": "#936300",
  "color-warning-900": "#7A4E00",
  "color-danger-100": "#FFE5D5",
  "color-danger-200": "#FFC5AB",
  "color-danger-300": "#FF9E81",
  "color-danger-400": "#FF7961",
  "color-danger-500": "#FF3B2D",
  "color-danger-600": "#DB2023",
  "color-danger-700": "#B71626",
  "color-danger-800": "#930E26",
  "color-danger-900": "#7A0826",
};

export type KittenColorT =
  | "color-primary-100"
  | "color-primary-200"
  | "color-primary-300"
  | "color-primary-400"
  | "color-primary-500"
  | "color-primary-600"
  | "color-primary-700"
  | "color-primary-800"
  | "color-primary-900"
  | "color-warning-100"
  | "color-warning-200"
  | "color-warning-300"
  | "color-warning-400"
  | "color-warning-500"
  | "color-warning-600"
  | "color-warning-700"
  | "color-warning-800"
  | "color-warning-900"
  | "color-danger-100"
  | "color-danger-200"
  | "color-danger-300"
  | "color-danger-400"
  | "color-danger-500"
  | "color-danger-600"
  | "color-danger-700"
  | "color-danger-800"
  | "color-danger-900"
  | "color-info-100"
  | "color-info-200"
  | "color-info-300"
  | "color-info-400"
  | "color-info-500"
  | "color-info-600"
  | "color-info-700"
  | "color-info-800"
  | "color-info-900"
  | "color-success-100"
  | "color-success-200"
  | "color-success-300"
  | "color-success-400"
  | "color-success-500"
  | "color-success-600"
  | "color-success-700"
  | "color-success-800"
  | "color-success-900"
  | "color-primary-focus"
  | "color-primary-hover"
  | "color-primary-default"
  | "color-primary-active"
  | "color-primary-disabled"
  | "background-basic-color-1"
  | "background-basic-color-2"
  | "background-basic-color-3"
  | "background-basic-color-4"
  | "border-basic-color-1"
  | "border-basic-color-2"
  | "border-basic-color-3"
  | "border-basic-color-4"
  | "border-basic-color-5"
  | "background-alternative-color-1"
  | "background-alternative-color-2"
  | "background-alternative-color-3"
  | "background-alternative-color-4"
  | "border-alternative-color-1"
  | "border-alternative-color-2"
  | "border-alternative-color-3"
  | "border-alternative-color-4"
  | "border-alternative-color-5"
  | "background-primary-color-1"
  | "background-primary-color-2"
  | "background-primary-color-3"
  | "background-primary-color-4"
  | "border-primary-color-1"
  | "border-primary-color-2"
  | "border-primary-color-3"
  | "border-primary-color-4"
  | "border-primary-color-5"
  | "text-basic-color"
  | "text-alternate-color"
  | "text-control-color"
  | "text-disabled-color"
  | "text-hint-color";

export const ColorSchemeE = {
  "color-primary-100": "color-primary-100",
  "color-primary-200": "color-primary-200",
  "color-primary-300": "color-primary-300",
  "color-primary-400": "color-primary-400",
  "color-primary-500": "color-primary-500",
  "color-primary-600": "color-primary-600",
  "color-primary-700": "color-primary-700",
  "color-primary-800": "color-primary-800",
  "color-primary-900": "color-primary-900",
  "color-warning-100": "color-warning-100",
  "color-warning-200": "color-warning-200",
  "color-warning-300": "color-warning-300",
  "color-warning-400": "color-warning-400",
  "color-warning-500": "color-warning-500",
  "color-warning-600": "color-warning-600",
  "color-warning-700": "color-warning-700",
  "color-warning-800": "color-warning-800",
  "color-warning-900": "color-warning-900",
  "color-danger-100": "color-danger-100",
  "color-danger-200": "color-danger-200",
  "color-danger-300": "color-danger-300",
  "color-danger-400": "color-danger-400",
  "color-danger-500": "color-danger-500",
  "color-danger-600": "color-danger-600",
  "color-danger-700": "color-danger-700",
  "color-danger-800": "color-danger-800",
  "color-danger-900": "color-danger-900",
  "color-info-100": "color-info-100",
  "color-info-200": "color-info-200",
  "color-info-300": "color-info-300",
  "color-info-400": "color-info-400",
  "color-info-500": "color-info-500",
  "color-info-600": "color-info-600",
  "color-info-700": "color-info-700",
  "color-info-800": "color-info-800",
  "color-info-900": "color-info-900",
  "color-success-100": "color-success-100",
  "color-success-200": "color-success-200",
  "color-success-300": "color-success-300",
  "color-success-400": "color-success-400",
  "color-success-500": "color-success-500",
  "color-success-600": "color-success-600",
  "color-success-700": "color-success-700",
  "color-success-800": "color-success-800",
  "color-success-900": "color-success-900",
  "color-primary-focus": "color-primary-focus",
  "color-primary-hover": "color-primary-hover",
  "color-primary-default": "color-primary-default",
  "color-primary-active": "color-primary-active",
  "color-primary-disabled": "color-primary-disabled",
  "background-basic-color-1": "background-basic-color-1",
  "background-basic-color-2": "background-basic-color-2",
  "background-basic-color-3": "background-basic-color-3",
  "background-basic-color-4": "background-basic-color-4",
  "border-basic-color-1": "border-basic-color-1",
  "border-basic-color-2": "border-basic-color-2",
  "border-basic-color-3": "border-basic-color-3",
  "border-basic-color-4": "border-basic-color-4",
  "border-basic-color-5": "border-basic-color-5",
  "background-alternative-color-1": "background-alternative-color-1",
  "background-alternative-color-2": "background-alternative-color-2",
  "background-alternative-color-3": "background-alternative-color-3",
  "background-alternative-color-4": "background-alternative-color-4",
  "border-alternative-color-1": "border-alternative-color-1",
  "border-alternative-color-2": "border-alternative-color-2",
  "border-alternative-color-3": "border-alternative-color-3",
  "border-alternative-color-4": "border-alternative-color-4",
  "border-alternative-color-5": "border-alternative-color-5",
  "background-primary-color-1": "background-primary-color-1",
  "background-primary-color-2": "background-primary-color-2",
  "background-primary-color-3": "background-primary-color-3",
  "background-primary-color-4": "background-primary-color-4",
  "border-primary-color-1": "border-primary-color-1",
  "border-primary-color-2": "border-primary-color-2",
  "border-primary-color-3": "border-primary-color-3",
  "border-primary-color-4": "border-primary-color-4",
  "border-primary-color-5": "border-primary-color-5",
  "text-basic-color": "text-basic-color",
  "text-alternate-color": "text-alternate-color",
  "text-control-color": "text-control-color",
  "text-disabled-color": "text-disabled-color",
  "text-hint-color": "text-hint-color",
};
