export const colors = {
  $light: {
    textPrimary: '#4a2702',
    textSecondary: '#865328',
    textInfo: '#d0763c',
    textDisable: '#e5ad8b',
    textButton: '#f8e4d5',
    backgroundPrimary: '#fff',
    backgroundSecondary: '#fbecdf',
    backgroundButton: '#c4540b',
    borderPrimary: '#f6d7bf',
    backgroundActive: '#c4540b',
    backgroundDisable: '#fbecdf',
    //
    textYellowPrimary: '#5d4713',
    textYellowSecondary: '#a58625',
    backgroundYellowPrimary: '#fdf6be',
    backgroundYellowSecondary: '#f5e27b',
    // borderYellow: '#c5b',
    //
    textBluePrimary: '#212a48',
    textBlueSecondary: '#293d77',
    backgroundBluePrimary: '#e2f0ff',
    backgroundBlueSecondary: '#95bbee',
    textGreenPrimary: '#1f5426',
    textGreenSecondary: '#0c730c',
    backgroundGreenPrimary: '#daf5eb',
    backgroundGreenSecondary: '#108835',
    textTealPrimary: '#043744',
    textTealSecondary: '#0d828d',
    backgroundTealPrimary: '#aae7ea',
    backgroundTealSecondary: '#13a2ad'
  },
  $dark: {
    textPrimary: '#f6d7bf',
    textSecondary: '#d17748',
    textInfo: '#e0a987',
    textDisable: '#e5ad8b',
    textButton: '#362308',
    backgroundPrimary: '#2c1b01',
    backgroundSecondary: '#000000',
    backgroundButton: '#e5ad8b',
    borderPrimary: '#d67a4a',
    backgroundActive: '#e5ad8b',
    backgroundDisable: '#000000',
    textYellowPrimary: '#fdf6be',
    textYellowSecondary: '#f1dd77',
    backgroundYellowPrimary: '#805501',
    backgroundYellowSecondary: '#422a00',
    textBluePrimary: '#d9eafd',
    textBlueSecondary: '#c2d5f1',
    backgroundBluePrimary: '#1358cc',
    backgroundBlueSecondary: '#1242a2',
    textGreenPrimary: '#d7f2e7',
    textGreenSecondary: '#97cbaf',
    backgroundGreenPrimary: '#108835',
    backgroundGreenSecondary: '#005301',
    textTealPrimary: '#b5d8da',
    textTealSecondary: '#aae7ea',
    backgroundTealPrimary: '#06505c',
    backgroundTealSecondary: '#043744'
  }
}
